#source /usr/share/git-core/contrib/completion/git-prompt.sh
source /usr/local/etc/profile.d/bash_completion.sh

# Dotfiles' root-dir
ROOT=${HOME}/

stty werase undef
bind '\C-w:unix-filename-rubout'

# Colors & functions
source ${ROOT}/bash/bash_colors
source ${ROOT}/bash/bash_functions

# export PS1='\[\e[1;37m\]|-- \[\e[1;32m\]\u\[\e[0;39m\]@buildvm:\[\e[1;36m\]\h\[\e[0;39m\]:\[\e[1;33m\]\w\[\e[0;39m\]\[\e[1;35m\]$(__git_ps1 " (%s)")\[\e[0;39m\] \[\e[1;37m\]--|\[\e[0;39m\]\n$ '
PATH="$HOME/.local/bin:$HOME/.cabal/bin:$HOME/bin:$PATH"
export PATH

# export PS1='$PWD$(__git_ps1)> '

# git config --global color.ui auto
# git config --global push.default tracking
# git config --global merge.conflictstyle diff3
# git config --global alias.br "branch -vv"
# git config --global alias.co "checkout"
# git config --global alias.base "pull --rebase"
# git config --global alias.force-push "push --force --force-with-lease"
# git config --global core.autocrlf input
# git config --global credential.helper cache
# git config --global credential.helper 'cache --timeout=3600'
# git config --global core.editor "vim"
# git config --global user.name "Avi Vigder"
# git config --global user.email avi.vigder@elastifile.com



# Bash history
export HISTSIZE=10000
export HISTCONTROL=ignoreboth:erasedups

# Prompt
#export PS1='[\u@\h \W]\$ '
export PROMPT_DIRTRIM=4
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWUPSTREAM="auto"
export PS1="[${GREEN}\u@\h${NORMAL} ${BRIGHT_VIOLET}\w${NORMAL}${NORMAL}]${BRIGHT_YELLOW}\$(__git_ps1)${NORMAL}\$ ${RESET}"

# Editor
export EDITOR=vim

# Aliases
alias ll='ls -lh'
alias ltr='ls -ltrh'
alias lss='ls -lhs'
alias la='ls -A'
alias l='ls -CF'
alias cd..='cd ..'
alias tree='tree -C -F --dirsfirst'
alias find-ch='find -type f -name "*.[ch]" '
alias grep='grep --color=auto'
# alias diff='diff --color=auto'
alias gs='git status'
alias gf='git fetch'
alias br='git br'
alias gb='git br'
alias gsr='git-search-replace.py'
alias rtc='resolve-trivial-conflicts -dc'

# Check the window size after each command and update
shopt -s checkwinsize

# Be generous to Java apps (eclipse)
# export _JAVA_OPTIONS="-Xms512m -Xmx1g"

# Have python history file
export PYTHONSTARTUP=${ROOT}/bash/pystartup
